# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-CPAN
version:      0.001
version_from: lib/Test/CPAN.pm
installdirs:  site
requires:
    Test::Deep:                    0.087

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
